### ISSUE TITLE
Add configuration file

### ISSUE THREAD

**Issue by jezevec10** [bhainesva/jstris-leaderboard-changes#2]
It would be great to have a configuration file where it would be possible to set TOP X of the leaderboard to be fetched.

If #1 gets added, the configuration file would also include a link for webhook URI.

In the future it could also include which game modes are read (for now only 40L Sprint is good enough). In this case it would be nice to have option to configure TOP X value for each gamemode, not globaly. This is because changes in TOP 100 of 1000L will be more common/easier to achieve than changes in TOP 100 40L.

**Comment by bhainesva** [comment]
I've added support for a config file, here's a sample of what the format looks like: https://github.com/bhainesva/jstris-leaderboard-changes/blob/main/config.json.

The script will use `config.json` by default or you can provide a custom path with a `-c / -config` option.

Let me know if there are any other options you'd like to have.

**Comment by jezevec10** [comment]
Very nice! I like these configuration file options.

Is it possible to configure in which order the messages appear in discord? I'm testing with 1000L and 40L and sometimes 1000L showed first and sometimes 40L. Since 40L is probably more interesting it would be nice to have option to configure in which order the messages appear (or keep order as they are defined in config json).

**Comment by bhainesva** [comment]
I've made some updates. The order of the output should match the order in the config file now. I also added a new `skipEmpty`config property. If it's set to true it won't post to discord if there aren't any changes for a particular leaderboard.

**Comment by jezevec10** [comment]
Thanks for the changes, I've updated  to the current version, everything in this ticket is now resolved, great work!
