### ISSUE TITLE
StatusError: Bad Request

### ISSUE THREAD

**Issue by jezevec10** [bhainesva/jstris-leaderboard-changes#6]
Hi, sorry for creating another issue, but I'm sure this will be the last problem before the script becomes flawless.
Today the changes weren't posted because of this Bad Request error:

```
StatusError: Bad Request
    at ClientRequest.<anonymous> (/home/jstris/jstris-leaderboard-changes/node_modules/bent/src/nodejs.js:133:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:509:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10) {
  statusCode: 400,
  json: [AsyncFunction (anonymous)],
  text: [Function (anonymous)],
  arrayBuffer: [Function (anonymous)],
```

I'm not sure what caused it or if it was because I put more modes into the config file, this is the config the error occurred on:
```
{
  "discordWebhook": "https://discord.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "skipEmpty": false,
  "reports": [
    {
      "name": "Sprint 20L",
      "game": 1,
      "mode": 2,
      "top": 400
    },
    {
      "name": "Sprint 40L",
      "game": 1,
      "mode": 1,
      "top": 500
    },
    {
      "name": "Sprint 100L",
      "game": 1,
      "mode": 3,
      "top": 400
    },
    {
      "name": "Sprint 1000L",
      "game": 1,
      "mode": 4,
      "top": 400
    },
    {
      "name": "Cheese 10L",
      "game": 3,
      "mode": 1,
      "top": 400
    },
    {
      "name": "Cheese 18L",
      "game": 3,
      "mode": 2,
      "top": 400
    },
    {
      "name": "Cheese 100L",
      "game": 3,
      "mode": 3,
      "top": 200
    },
    {
      "name": "Survival",
      "game": 4,
      "mode": 1,
      "top": 400
    },
    {
      "name": "Ultra",
      "game": 5,
      "mode": 1,
      "formatTime": false,
      "top": 400
    }
  ]
}

```

**Comment by bhainesva** [comment]
It looks like this was happening because discord has a 2000char length limit on messages. I updated it to split long updates into separate posts.

The reason the update was so long was that a player who was ranked ~400 on the leaderboard became hidden which caused everyone below them to move up one slot.

**Comment by jezevec10** [comment]
Thanks for explaining the cause of this, that makes sense.

I think this output should be prevented because it's taking a lot of space in discord channel and from the output it's not really clear who actually improved and who moved up just because someone else was hidden.

It could be solved like this: check `ts` (timestamp) param from the jstris API response and if the record would show in the change as ▲(`changeType.RISE` or `changeType.ENTER`), include it in the report only if it was achieved in the last 24 hours. That way old records won't spam the report if they would appear only because someone made their account hidden.

Ideally the 24 hours could be configurable in the config file, because the leaderboard cache updates every 24 hours but it's not instant until it updates, so the script runs about 1-2 hours after the leaderboard cache updates making it necessary to set more than 24 to avoid some early scores that day being ignored when they shouldn't.

![image](https://user-images.githubusercontent.com/7414891/100074155-b38acc00-2e3e-11eb-9bff-7d93c0fa24cf.png)

**Comment by bhainesva** [comment]
Hey @jezevec10, I've added some logic to filter out any rank increases where the timestamp of the new score is the same as the timestamp of the old score. I hope this will address the issue and was a little simpler for me than adding new config options. But let me know if it isn't sufficient.

**Comment by jezevec10** [comment]
Hi @bhainesva thanks for the update. I've installed it and so far it seems good. If more problems appear in the fututre I'll open another issue, but it seems now the script is finished.
I've added your username and a link to this repository to _Feature contributions_ section on [https://jstris.jezevec10.com/about](https://jstris.jezevec10.com/about). Thanks for providing this script!
